<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name = "ntarobot">
    <!-- Seccion de importe de archivos -->
    <!-- Propiedades de materiales y medida de las piezas -->
    <xacro:include filename="$(find ntarobot_urdf)/urdf/ntarobot_matprop.xacro"/>
    <!-- Importe de valores de inercia de las piezas (Falta calcular)-->
    <xacro:include filename="$(find ntarobot_urdf)/urdf/ntarobot_intertial.xacro"/>
    <!-- Fin de importe de archivos -->

    <!-- Inicio de creacion de propiedades nuevas -->
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="imu_mass" value="0.05"/>
    <xacro:property name="camera_mass" value="0.05"/>
    <xacro:property name="wheel_mass" value="0.3"/>
    <xacro:property name="lidar_mass" value="0.05"/>
    <!-- Fin de creacion de propiedades -->

    <!-- Seccion de creacion de modelo -->
    <!-- Primero va creada la seccion del footprint del robot, como la base de la estructura entendiendo que es una estructura cuadrada -->
    <link name="base_footprint"/>

    <!-- Seccion de estructura y figuras del robot -->
    <!-- Primera seccion de la caja principal del robot -->
    <link name="base_link">
        <!-- Especificaciones visuales de la primera forma -->
        <visual>
            <!-- Posicion inicial de la figura -->
            <!-- En este caso el valor de 0.0225, es la diferencia entre diferencias del suelo y la altura de la caja-->
            <origin xyz="0 0 ${chassis_width/2 - 0.0225}" rpy="0.0 0.0 0.0"/>
            <!-- Estructura geometrica de la figura en cuestion -->
            <geometry>
                <box size="${chassis_length} ${chassis_height} ${chassis_width}"/>
            </geometry>
            <!-- Control del tipo de material de la carcaza general -->
            <material name="blue"/>
        </visual>
        <!-- Especificaciones de inercia para cada pieza-->
        <collision>
            <origin xyz="0 0 ${chassis_width/2 - 0.0225}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_height} ${chassis_width}"/>
            </geometry>
        </collision>
        <!-- Calculo de la inercia con las funciones creadas -->
        <xacro:inertial_box mass="${chassis_mass}" x="${chassis_length}" y="${chassis_height}" z="${chassis_width}">
            <origin xyz="0 0 ${chassis_width/2 - 0.0225}" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <!-- Seccion de creacion de articulacion de la base del robot -->
    <joint name="base_joint" type="fixed">
        <!-- Seccion de relacion jerarquica -->
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <!-- Seccion de origen del chassis del robot -->
        <!-- En este caso el valor de 0.0695, corresponde al valor de diferencia de la caja principal con respecto al suelo-->
        <origin xyz="0.0 0.0 0.0695" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Sigue la estructura de las llandas del robot -->
    <!-- Primero disenamos la llanta posterior derecha -->
    <link name="wheel_front_right_link">
        <visual>
            <!-- Corresponde al ppunto de inicio de la rueda -->
            <origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
            <geometry>
                <!-- Corresponde a las dimensiones precisas de la rueda -->
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <!-- Seccion de calculo de colisiiones -->
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <!-- Seccion de calculo de inercia -->
        <xacro:inertial_cylinder mass ="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Sigue la seccion del joint de la rueda frontal -->
    <joint name="wheel_front_right_joint" type="continuous">
        <!-- Relacion de jerarquia -->
        <parent link="base_link"/>
        <child link="wheel_front_right_link"/>
        <!-- Posicionamiento incial de las ruedas -->
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="0.163 -0.2025 0.0" rpy="0.0 0.0 0.0"/>
        <!-- Establece la relaccion de mimica de la articulacion -->
        <!-- <mimic joint="wheel_back_right_joint"/> -->
    </joint>

    <!-- Seguido de la llanda trasera derecha, de tal manera que esta este conectada a la derecha posterior -->
    <link name="wheel_back_right_link">
        <visual>
            <!-- Corresponde al ppunto de inicio de la rueda -->
            <origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
            <geometry>
                <!-- Corresponde a las dimensiones precisas de la rueda -->
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <!-- Seccion de calculo de colisiiones -->
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <!-- Seccion de calculo de inercia -->
        <xacro:inertial_cylinder mass ="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="1.57 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Sigue la seccion del joint de la rueda frontal -->
    <joint name="wheel_back_right_joint" type="continuous">
        <!-- Relacion de jerarquia -->
        <parent link="base_link"/>
        <child link="wheel_back_right_link"/>
        <!-- Posicionamiento incial de las ruedas -->
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="-0.163 -0.2025 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Ahora el posicionamiento de las ruedas de la izquierda del robot.-->
    <!-- llanta frontal izquerda -->
    <link name="wheel_front_left_link">
        <visual>
            <!-- Corresponde al ppunto de inicio de la rueda -->
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 0.0"/>
            <geometry>
                <!-- Corresponde a las dimensiones precisas de la rueda -->
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <!-- Seccion de calculo de colisiiones -->
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <!-- Seccion de calculo de inercia -->
        <xacro:inertial_cylinder mass ="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Sigue la seccion del joint de la rueda frontal -->
    <joint name="wheel_front_left_joint" type="continuous">
        <!-- Relacion de jerarquia -->
        <parent link="base_link"/>
        <child link="wheel_front_left_link"/>
        <!-- Posicionamiento incial de las ruedas -->
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="0.163 0.2025 0.0" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Asi mismo creamos la rueda trasera izquierda-->
    <link name="wheel_back_left_link">
        <visual>
            <!-- Corresponde al ppunto de inicio de la rueda -->
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 0.0"/>
            <geometry>
                <!-- Corresponde a las dimensiones precisas de la rueda -->
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <!-- Seccion de calculo de colisiiones -->
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 0.0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <!-- Seccion de calculo de inrecia -->
        <xacro:inertial_cylinder mass ="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="-1.57 0.0 0.0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- Sigue la seccion del joint de la rueda trasera -->
    <joint name="wheel_back_left_joint" type="continuous">
        <!-- Relacion de jerarquia -->
        <parent link="base_link"/>
        <child link="wheel_back_left_link"/>
        <!-- Posicionamiento incial de las ruedas -->
        <axis xyz="0.0 1.0 0.0"/>
        <origin xyz="-0.163 0.2025 0.0" rpy="0.0 0.0 0.0"/>
        <!-- Establecemos la relacion entre las 2 -->
        <!-- <mimic joint="wheel_front_left_joint"/> -->
    </joint>

    <link name = "imu_link">
        <!-- Especificaciones visuales de la primera forma -->
        <visual>
            <!-- Posicion inicial de la figura -->
            <!-- En este caso el valor de 0.0225, es la diferencia entre diferencias del suelo y la altura de la caja-->
            <origin xyz="0 0 ${imu_width/2}" rpy="0.0 0.0 0.0"/>
            <!-- Estructura geometrica de la figura en cuestion -->
            <geometry>
                <box size="${imu_length} ${imu_height} ${imu_width}"/>
            </geometry>
            <!-- Control del tipo de material de la carcaza general -->
            <material name="white"/>
        </visual>
        <!-- Especificaciones de inercia para cada pieza-->
        <collision>
            <origin xyz="0 0 ${imu_width/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${imu_length} ${imu_height} ${imu_width}"/>
            </geometry>
        </collision>
        <!-- Calculo de la inercia con las funciones creadas -->
        <xacro:inertial_box mass="${imu_mass}" x="${imu_length}" y="${imu_height}" z="${imu_width}">
            <origin xyz="0 0 ${imu_width/2}" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_box>
    </link>

    <joint name="imu_link" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <!-- <origin xyz="0.0 0.0 0.283 - 0.047" rpy="0.0 0.0 0.0"/> -->
        <origin xyz="0.0 0.0 0.236" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <!-- Seccion de anexo de la camara -->
     <link name="camera_link">
        <visual name="">
            <origin xyz="${camera_length/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_height} ${camera_width}"/>
            </geometry>
            <material name="camera-color"/>
        </visual>
     </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <!-- <origin xyz="0.0 0.0 0.283 - 0.047" rpy="0.0 0.0 0.0"/> -->
        <origin xyz="0.20 0.0 0.18" rpy="0.0 0.0 0.0"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>

    <!-- Seccion de creacion e ingreso de posicion especifica del lidar -->
     <link name="lidar_link">
        <!-- Primero va la descripcion visual del lidar -->
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_thickness}"/>
            </geometry>
            <material name="lidar-color"/>
        </visual>
        <!-- Finalmente se describe las caracteristicas de colision de lidar -->
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_thickness}"/>
            </geometry>
        </collision>
        <!-- Descripcion inercial del lidar -->
        <xacro:inertial_cylinder mass ="${lidar_mass}" length="${lidar_thickness}" radius="${lidar_radius}">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </xacro:inertial_cylinder>
     </link>

     <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <!-- <origin xyz="0.0 0.0 0.283 - 0.047" rpy="0.0 0.0 0.0"/> -->
        <origin xyz="0.0 0.0 0.296" rpy="0.0 0.0 3.14159"/>
    </joint>
</robot>
